import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "~/components/header/header";
import MainReddits from "~/components/main/main";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Reddit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true} className={inter.className}>
        <Header />
        <MainReddits>{children}</MainReddits>
      </body>
    </html>
  );
}
